### ISSUE TITLE
您好，比赛官方的数据下载渠道关闭了，能不能共享下比赛的30万数据。万分感谢！

### ISSUE THREAD

**Issue by kyang888** [yanx27/DuReader_QANet_BiDAF#2]

**Comment by yanx27** [comment]
可以从这个网址下载完整的DuReader http://ai.baidu.com/broad/download

**Comment by kYang109451** [comment]
> 可以从这个网址下载完整的DuReader http://ai.baidu.com/broad/download

您好，DuReader官网的数据是这样划分的，test set 是60000，验证集小于10000， 训练集13万，感觉划分的不是很好。
